name: Trigger deploy on a schedule if changes occurred since last deploy

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Check last change
        id: check_last_change
        run: |
          LAST_COMMIT=$(git show --no-patch --format=%ct HEAD)
          LAST_CTFL_CHANGE=$(node ./.github/scripts/get-latest-contentful-entry.js)

          CURRENT_TS=$(date +%s)
          DAY_SEC=$((24 * 60 * 60))
          DATE_24HRS_AGO=$(($CURRENT_TS - $DAY_SEC))

          [ $LAST_COMMIT -ge $DATE_24HRS_AGO -o $LAST_CTFL_CHANGE -ge $DATE_24HRS_AGO ] && result="true" || result="false"
          echo "deploy_needed=$result" >> $GITHUB_OUTPUT
        env:
          CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
          CTFL_ACCESSTOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}

  deploy:
    needs: check-deploy
    if: needs.check_deploy.outputs.deploy_needed == 'true'
    runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy.yml
    secrets:
      CTFL_ACCESSTOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}
      CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
